{{- if .Values.volumes.customModules.persistentVolumeClaim.create }}
{{- $pvcCheck := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace ( include "spotfire-common.volumes.customModules.pvc.name" . )) }}
{{- if not $pvcCheck }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spotfire-common.volumes.customModules.pvc.name" . }}
  labels:
  {{- include "spotfire-common.spotfire-service.labels" (merge . (dict "componentName" "webplayer")) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.customModules.persistentVolumeClaim.storageClassName | quote }}
  {{- with .Values.volumes.customModules.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  volumeName: {{ .Values.volumes.customModules.persistentVolumeClaim.volumeName | quote }}
{{- end }}
{{- end }}