{
 "title": "Spotfire Platform Kubernetes Environments",
 "tags": [ "Spotfire" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(spotfire_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Versions",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (capability, version, technicalVersion)(spotfire_build_info{namespace=\"$namespace\"})  ",
     "legendFormat": "{{capability}}: {{version}} {{technicalVersion}}"
    },
    {
     "expr": "sum by (capability, version, technicalVersion)(spotfire_worker_build_info{namespace=\"$namespace\"})",
     "legendFormat": "{{capability}}: {{version}} {{technicalVersion}}"
    },
    {
     "expr": "sum by ( version)(fluentbit_build_info{namespace=\"$namespace\"})  ",
     "legendFormat": "fluent-bit: {{version}}"
    },
    {
     "expr": "sum by ( version)(haproxy_process_build_info{namespace=\"$namespace\"})  ",
     "legendFormat": "haproxy: {{version}}"
    }
   ]
  },
  {
   "title": "Instances Down",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\"}==0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSS Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "spotfire_SpotfireServer_Server_UptimeMs{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Opened Web Player Analysis and Active Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spotfire_TIBCO_Spotfire_Webplayer_open_documents{namespace=\"$namespace\"})",
     "legendFormat": "Web Player Open Documents"
    },
    {
     "expr": "sum(spotfire_TIBCO_Spotfire_Webplayer_concurrent_users{namespace=\"$namespace\"})",
     "legendFormat": "Web Player Concurrent Users"
    },
    {
     "expr": "max(spotfire_SpotfireServer_ServerMetrics_AuthenticatedSessions{namespace=\"$namespace\"})",
     "legendFormat": "TSS Authenticated Sessions"
    },
    {
     "expr": "sum(spotfire_SpotfireServer_ServerMetrics_Sessions{namespace=\"$namespace\"}) ",
     "legendFormat": "TSS Local Sessions"
    },
    {
     "expr": "max(spotfire_ApacheIgnite_Size{counter_instance=\"spotfire-session-store\", namespace=\"$namespace\"})",
     "legendFormat": "TSS Clustered Sessions"
    }
   ]
  },
  {
   "title": "WorkerHost Health Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(capability)(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\"} == 0)",
     "legendFormat": "Available {{capability}}"
    },
    {
     "expr": "count by(capability)(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\"} == 5)",
     "legendFormat": "Strained {{capability}}"
    },
    {
     "expr": "count by(capability)(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\"} == 8)",
     "legendFormat": "Exhausted {{capability}}"
    }
   ]
  },
  {
   "title": "Opened Web Player Analysis per instance",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(spotfire_TIBCO_Spotfire_Webplayer_open_documents{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Users per instance",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(spotfire_TIBCO_Spotfire_Webplayer_concurrent_users{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Capability Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* (sum by(capability)(spotfire_service_usage_capacity{namespace=\"$namespace\"}) / (count by(capability)(spotfire_service_usage_capacity{namespace=\"$namespace\"}) * 100))",
     "legendFormat": "{{capability}}"
    },
    {
     "expr": "100* (sum(spotfire_TIBCO_Spotfire_Automation_Services_Active_jobs{namespace=\"$namespace\"}) / sum(spotfire_TIBCO_Spotfire_Automation_Services_Automation_services_slots_capacity{namespace=\"$namespace\"}) )",
     "legendFormat": "AUTOMATION_SERVICES"
    },
    {
     "expr": "100*( sum(spotfire_TIBCO_Spotfire_Webplayer_analyses_currently_loading_by_scheduled_updates{namespace=\"$namespace\"})/ (sum(spotfire_TIBCO_Spotfire_Webplayer_available_scheduled_updates_slots{namespace=\"$namespace\"})+sum(spotfire_TIBCO_Spotfire_Webplayer_analyses_currently_loading_by_scheduled_updates{namespace=\"$namespace\"})))",
     "legendFormat": "SCHEDULED UPDATES"
    }
   ]
  },
  {
   "title": "Scheduled Updates & Automation Services Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spotfire_TIBCO_Spotfire_Webplayer_analyses_under_scheduled_updates_control{namespace=\"$namespace\"})",
     "legendFormat": "Analysis Loaded"
    },
    {
     "expr": "sum(spotfire_TIBCO_Spotfire_Webplayer_analyses_currently_loading_by_scheduled_updates{namespace=\"$namespace\"})",
     "legendFormat": "Analysis Loading"
    },
    {
     "expr": "sum(spotfire_TIBCO_Spotfire_Automation_Services_Active_jobs{namespace=\"$namespace\"})",
     "legendFormat": "Jobs Active"
    },
    {
     "expr": "sum(spotfire_TIBCO_Spotfire_Webplayer_available_scheduled_updates_slots{namespace=\"$namespace\"})",
     "legendFormat": "Available Slots"
    }
   ]
  },
  {
   "title": "Service Process Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(capability, status) (spotfire_nodemanager_services{namespace=\"$namespace\"}) > 0",
     "legendFormat": "{{capability}} {{status}}"
    },
    {
     "expr": "sum by (app_kubernetes_io_component, status) (spotfire_tss_status{namespace=\"$namespace\"}) > 0 ",
     "legendFormat": "{{app_kubernetes_io_component}} {{status}}"
    }
   ]
  },
  {
   "title": "Job Queuing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(counter_instance) (spotfire_Jobs_QueueSize{namespace=\"$namespace\"})",
     "legendFormat": "Job Queue: {{counter_instance}}"
    }
   ]
  },
  {
   "title": "Total number of current TSS Requests per \"entry point\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(counter_instance)(spotfire_WebServices_Requests_current{namespace=\"$namespace\"})",
     "legendFormat": "{{counter_instance}}"
    }
   ]
  },
  {
   "title": "Information Services",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job) (spotfire_SpotfireServer_ServerMetrics_InformationServicesJobs{namespace=\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "(spotfire_SpotfireServer_ServerMetrics_InformationServicesJobs{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(job) (spotfire_InformationServices_InformationServicesMetrics_InformationServicesJobs{namespace=\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "(spotfire_InformationServices_InformationServicesMetrics_InformationServicesJobs{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSS G1 Young Generation CollectionTime 1 min rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(spotfire_GC_GarbageCollector_CollectionTime{namespace=\"$namespace\", app_kubernetes_io_component=\"server\", counter_instance=\"G1 Young Generation\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSS G1 Young Generation CollectionCount 1 min rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(spotfire_GC_GarbageCollector_CollectionCount{namespace=\"$namespace\", app_kubernetes_io_component=\"server\", counter_instance=\"G1 Young Generation\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSS Heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "spotfire_MEMORY_Memory_HeapMemoryUsage_used{namespace=\"$namespace\", app_kubernetes_io_component=\"server\"}",
     "legendFormat": "{{app_kubernetes_io_component}} {{pod}}"
    }
   ]
  },
  {
   "title": "Load Balancer Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{namespace=\"$namespace\", frontend=\"http-caching\"}",
     "legendFormat": "Frontend Sessions"
    },
    {
     "expr": "haproxy_server_current_sessions{namespace=\"$namespace\"} > 0",
     "legendFormat": "Sessions {{server}}"
    }
   ]
  },
  {
   "title": "TSS Threads Busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spotfire_WebServer_ThreadPool_currentThreadsBusy{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} {{counter_instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*spotfire_OS_OperatingSystem_ProcessCpuLoad{namespace=\"$namespace\", app_kubernetes_io_component=\"server\"}",
     "legendFormat": "{{app_kubernetes_io_component}}:{{pod}}"
    },
    {
     "expr": "100*spotfire_OS_OperatingSystem_SystemCpuLoad{namespace=\"$namespace\", app_kubernetes_io_component=\"server\"}",
     "legendFormat": "machine: {{app_kubernetes_io_component}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Load Balancer request rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_requests_total{proxy=\"spotfire\", namespace=\"$namespace\"}[1m])  ",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "TSS Http & WS Request Rate (1 minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(spotfire_WebServer_GlobalRequestProcessor_requestCount{counter_instance=~\"https-jsse-nio2-9443|https-jsse-nio-9443\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Backend Connector"
    },
    {
     "expr": "sum by (job) ( irate(spotfire_SpotfireServer_WebPlayerWebSocketMetrics_SentClientMessages{namespace=\"$namespace\"}[1m]) )",
     "legendFormat": "Websocket Sent Messages"
    },
    {
     "expr": "sum by (job) (irate(spotfire_WebServer_GlobalRequestProcessor_requestCount{counter_instance=~\"http-nio-80|http-nio2-80|http-nio2-8080|http-nio-8080\",namespace=\"$namespace\"}[1m]))  ",
     "legendFormat": "Frontend Connector"
    },
    {
     "expr": "sum by (job) ( irate(spotfire_SpotfireServer_WebPlayerWebSocketMetrics_RecievedClientMessages{namespace=\"$namespace\"}[1m]) )",
     "legendFormat": "Websocket Recieved Messages"
    }
   ]
  },
  {
   "title": "TSS Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spotfire_SpotfireServer_DataSource_CurrentIdleCount{namespace=\"$namespace\"}",
     "legendFormat": "TSS DB Idle Connections {{pod}}"
    },
    {
     "expr": "spotfire_SpotfireServer_DataSource_Acquisition1MinuteRate{namespace=\"$namespace\"}",
     "legendFormat": "TSS DB Acquisition1MinuteRate {{pod}}"
    },
    {
     "expr": "spotfire_SpotfireServer_DataSource_CurrentActiveCount{namespace=\"$namespace\"}",
     "legendFormat": "TSS DB Active Connections {{pod}}"
    }
   ]
  },
  {
   "title": "Load Balancer response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=\"spotfire\",namespace=\"$namespace\"}",
     "legendFormat": "Average Response Time"
    }
   ]
  },
  {
   "title": "Worker Http & WS Request Rate (1 minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(spotfire_TIBCO_Spotfire_Web_Service_WCF_Calls_accumulated_All{namespace=\"$namespace\"}[60s]))",
     "legendFormat": "Worker WCF Calls"
    },
    {
     "expr": "sum (rate(spotfire_TIBCO_Spotfire_Webplayer_WebSocket_messages_sent{namespace=\"$namespace\"}[60s]))",
     "legendFormat": "Web Player Sent Websocket Messages"
    }
   ]
  },
  {
   "title": "Webplayer Thread Pool Queuelength",
   "type": "timeseries",
   "description": "Sustained high or flat non-zero levels may indicate a \"hanging\" instance. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spotfire_TIBCO_Spotfire_Threading_thread_pool_queue_length{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} {{serviceId}}"
    }
   ]
  },
  {
   "title": "Load Balanser I/O Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{proxy=\"spotfire\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "I/O In"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{proxy=\"spotfire\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "I/O Out"
    }
   ]
  },
  {
   "title": "Spotfire Server I/O Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(counter_instance) (irate(spotfire_WebServer_GlobalRequestProcessor_bytesReceived{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "I/O In {{counter_instance}}"
    },
    {
     "expr": "sum by(counter_instance) (irate(spotfire_WebServer_GlobalRequestProcessor_bytesSent{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "I/O Out {{counter_instance}}"
    }
   ]
  },
  {
   "title": "Webplayer Active Threads and Data Engine queries",
   "type": "timeseries",
   "description": "Sustained high levels may indicate a \"hanging\" instance. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spotfire_TIBCO_Spotfire_Threading_active_threads_in_thread_pool{namespace=\"$namespace\"}",
     "legendFormat": "Threads: {{pod}} {{serviceId}}"
    },
    {
     "expr": "spotfire_TIBCO_Spotfire_Data_Engine_no_queries{namespace=\"$namespace\"}",
     "legendFormat": "Queries: {{pod}} {{serviceId}}"
    }
   ]
  },
  {
   "title": "Static Resources Cache Hits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_http_cache_hits_total{proxy=\"spotfire\", namespace=\"$namespace\"})/sum(haproxy_frontend_http_cache_lookups_total{proxy=\"spotfire\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "TSS SOAP Calls Rate 1 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod)(irate(spotfire_WebServices_Requests_total{namespace=\"$namespace\", counter_instance!~\"WebPlayer.*\", counter_instance!=\"global\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Used Worker Memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (spotfire_TIBCO_Spotfire_Webplayer_Available_memory{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{capability}} {{pod}} {{serviceId}}"
    }
   ]
  },
  {
   "title": "Data Functions - Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(capability)(spotfire_service_queue_engines_inUse) ",
     "legendFormat": "{{capability}}"
    }
   ]
  },
  {
   "title": "Worker CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(capability, pod)(spotfire_TIBCO_Spotfire_Webplayer_Total_average_processor{namespace=\"$namespace\"})",
     "legendFormat": "{{capability}} {{pod}}"
    }
   ]
  },
  {
   "title": "Worker Process Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "spotfire_Process_Private_Bytes{namespace=\"$namespace\"}",
     "legendFormat": "Process {{pod}}-{{serviceId}}"
    },
    {
     "expr": "spotfire_System_Runtime_working_set{namespace=\"$namespace\"}",
     "legendFormat": "Process {{pod}}-{{serviceId}}"
    }
   ]
  },
  {
   "title": "Worker Data Engine Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "spotfire_TIBCO_Spotfire_Data_Engine_system_allocated{namespace=\"$namespace\"}",
     "legendFormat": "Data Engine: {{pod}}-{{serviceId}}"
    }
   ]
  },
  {
   "title": "Worker Large Object Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "spotfire_System_Runtime_loh_size{namespace=\"$namespace\"}",
     "legendFormat": "LOH {{pod}}-{{serviceId}}"
    },
    {
     "expr": "spotfire_NET_CLR_Memory_Large_Object_Heap_size{namespace=\"$namespace\"}",
     "legendFormat": "LOH {{pod}}-{{serviceId}}"
    }
   ]
  },
  {
   "title": "Web Player Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\", capability=\"WEB_PLAYER\"} == 0) OR vector(0)",
     "legendFormat": "Available"
    },
    {
     "expr": "count(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\", capability=\"WEB_PLAYER\"} == 5) OR vector(0)",
     "legendFormat": "Strained"
    },
    {
     "expr": "count(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\", capability=\"WEB_PLAYER\"} == 8)  OR vector(0)",
     "legendFormat": "Exhausted"
    },
    {
     "expr": "count(spotfire_TIBCO_Spotfire_Webplayer_Web_Player_health_status{namespace=\"$namespace\", capability=\"WEB_PLAYER\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}