{{- if .Values.podDeletionCost.enabled -}}
{{- $context := mergeOverwrite (dict) . (dict "componentName" "terrservice") -}}
{{ include "spotfire-common.poddeletioncost.serviceAccount" $context }}
---
{{ include "spotfire-common.poddeletioncost.role" $context }}
---
{{ include "spotfire-common.poddeletioncost.roleBinding" $context }}
---
{{ include "spotfire-common.poddeletioncost.configMap" $context }}
---
{{ include "spotfire-common.poddeletioncost.deployment" $context }}
{{- end -}}
