SPOTFIRE_CDK_VERSION=4.2.1

# appVersions / images
SPOTFIRE_DEPLOYMENT_VERSION=14.6.2 HF-009
SPOTFIRE_NETCORE_LANGUAGEPACKS_VERSION=14.6.2
SPOTFIRE_NETCORE_VERSION=14.6.2 HF-009
SPOTFIRE_NODEMANAGER_VERSION=14.6.2
SPOTFIRE_PYTHONSERVICE_VERSION=1.23.2
SPOTFIRE_RSERVICE_VERSION=1.23.2
SPOTFIRE_SERVER_VERSION=14.6.2
SPOTFIRE_TERRSERVICE_VERSION=1.23.2

# Spotfire charts versions
SPOTFIRE_AUTOMATIONSERVICES_CHART_VERSION=2.2.1
SPOTFIRE_COMMON_CHART_VERSION=2.2.1
SPOTFIRE_RSERVICE_CHART_VERSION=2.2.1
SPOTFIRE_PYTHONSERVICE_CHART_VERSION=2.2.1
SPOTFIRE_SERVER_CHART_VERSION=2.2.1
SPOTFIRE_TERRSERVICE_CHART_VERSION=2.2.1
SPOTFIRE_WEBPLAYER_CHART_VERSION=2.2.1
SPOTFIRE_PLATFORM_CHART_VERSION=2.2.1
