{{- if .Values.cliPod.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name "cli" | quote }}
  labels:
    {{- include "spotfire-server.cli.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spotfire-server.cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.cliPod.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spotfire-server.cli.labels" . | nindent 8 }}
    spec:
      {{- include "spotfire-server.cliPod.imagePullSecrets" . | nindent 6}}
      serviceAccountName: {{ include "spotfire-server.serviceAccountName" . }}
      {{- if .Values.cliPod.extraInitContainers }}
      initContainers:
        {{- tpl (toYaml .Values.cliPod.extraInitContainers) $ | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: spotfire-cli
          command: ["/bin/sh", "-c"]
          args: ["trap 'exit 0' TERM; while true; do sleep 3600 & wait; done"]
          image: {{ include "spotfire-server.cliPod.image" . }}
          imagePullPolicy: {{ include "spotfire-server.cliPod.image.pullPolicy" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.volumes.certificates.existingClaim }}
            - name: {{ .Values.volumes.certificates.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/certs
              subPath: {{ .Values.volumes.certificates.subPath | quote }}
            {{- end }}
            {{- if .Values.volumes.customExt.existingClaim }}
            - name: {{ .Values.volumes.customExt.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/custom-ext
              subPath: {{ .Values.volumes.customExt.subPath | quote }}
            {{- end }}
            {{- if .Values.volumes.customExtInformationservices.existingClaim }}
            - name: {{ .Values.volumes.customExtInformationservices.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/custom-ext-informationservices
              subPath: {{ .Values.volumes.customExtInformationservices.subPath | quote }}
            {{- end }}
            {{- with .Values.cliPod.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
              {{/*
              - secretRef:
                  name: {{ template "spotfire-server.spotfiredatabase.secret.name" . }}
              */}}
            {{- if .Values.cliPod.extraEnvVarsSecret }}
            - secretRef:
                name: {{ tpl .Values.cliPod.extraEnvVarsSecret $ }}
            {{- end }}
            {{- if .Values.cliPod.extraEnvVarsCM }}
            - configMapRef:
                name: {{ tpl .Values.cliPod.extraEnvVarsCM $ }}
            {{- end }}
          env:
            {{- if .Values.cliPod.extraEnvVars }}
            {{ tpl (toYaml .Values.cliPod.extraEnvVars) $ | nindent 12 }}
            {{- end }}
            {{- include "spotfire-server.configVars" . | nindent 12 -}}
            {{- include "spotfire-common.acceptEUAEnvVar" . | nindent 12 }}
            {{- include "spotfire-server.site.envVars" . | nindent 12 }}
            {{- include "spotfire-server.database.envVars" . | nindent 12 }}
            - name: LOG_LEVEL
              value: {{ .Values.cliPod.logLevel | quote }}
      volumes:
        {{- $existingVolumes := dict }}
        {{- if .Values.volumes.certificates.existingClaim }}
        {{- $claimName := .Values.volumes.certificates.existingClaim }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
        {{- end }}
        {{ if .Values.volumes.customExt.existingClaim -}}
          {{- $claimName := .Values.volumes.customExt.existingClaim  }}
            {{- if not (index $existingVolumes $claimName) }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
          {{- end }}
        {{- end }}
        {{ if .Values.volumes.customExtInformationservices.existingClaim -}}
          {{- $claimName := .Values.volumes.customExtInformationservices.existingClaim  }}
            {{- if not (index $existingVolumes $claimName) }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
          {{- end }}
        {{- end }}
      {{- with .Values.cliPod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cliPod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cliPod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}