apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotfire-server.fullname" . }}
  labels:
    {{- include "spotfire-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.configuration.draining.publishNotReadyAddresses }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9443
      name: backend 
      protocol: TCP
      targetPort: 9443
    - port: 9080
      name: registration
      protocol: TCP
      targetPort: 9080
    - port: 9081
      name: monitoring
      protocol: TCP
      targetPort: 9081
  selector:
    {{- include "spotfire-server.selectorLabels" . | nindent 4 }}
