{{- if .Values.haproxy.enabled }}
{{- if ne .Values.service.type "ClusterIP" }}
{{- fail ".Values.service.type must be ClusterIP if .Values.haproxy.enabled is true" }}
{{- end }}
{{- if ne .Values.service.clusterIP "None" }}
{{- fail ".Values.service.clusterIP must be None if .Values.haproxy.enabled is true" }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotfire-server.fullname" . }}
  labels:
    {{- include "spotfire-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.configuration.draining.publishNotReadyAddresses }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9443
      name: backend 
      protocol: TCP
      targetPort: 9443
    - port: 9080
      name: registration
      protocol: TCP
      targetPort: 9080
    - port: 9081
      name: monitoring
      protocol: TCP
      targetPort: 9081
  selector:
    {{- include "spotfire-server.selectorLabels" . | nindent 4 }}
