{{- if not (and .Values.database.bootstrap.passwordExistingSecret.name .Values.configuration.spotfireAdmin.passwordExistingSecret.name) -}}
{{- $secretName := (include "spotfire-server.fullname" .) -}}
{{- $secretCheck := (lookup "v1" "Secret" .Release.Namespace $secretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    {{- include "spotfire-server.labels" . | nindent 4 }}
  name: {{ $secretName }}
data:
{{- if (not .Values.database.bootstrap.passwordExistingSecret.name) }}
  {{- if .Values.database.bootstrap.password }}
  SPOTFIREDB_PASSWORD: {{ .Values.database.bootstrap.password | b64enc | quote }}
  {{- else if $secretCheck }}
  SPOTFIREDB_PASSWORD: {{ index $secretCheck.data "SPOTFIREDB_PASSWORD" | default (randAlphaNum 12 | b64enc) | quote }}
  {{- else }}
  SPOTFIREDB_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if (not .Values.configuration.spotfireAdmin.passwordExistingSecret.name) }}
  {{- if .Values.configuration.spotfireAdmin.password }}
  SPOTFIREADMIN_PASSWORD: {{ .Values.configuration.spotfireAdmin.password  | b64enc | quote }}
  {{- else if $secretCheck }}
  SPOTFIREADMIN_PASSWORD: {{ index $secretCheck.data "SPOTFIREADMIN_PASSWORD" | default (randAlphaNum 12 | b64enc) | quote }}
  {{- else }}
  SPOTFIREADMIN_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
{{- end -}}
{{- end -}}
