# When using this chart, you should override the values in this file or provide
# a values file with your own values during installation. values-*.yaml for
# various examples.
spotfire-server:
  configuration:
    actionLog:
      categories: "admin,library,monitoring,info_link,routing_info"
      webCategories: "all"
      file:
        enabled: true
      database:
        enabled: true
        create-actionlogdb:
          enabled: true
          actiondbDbname: "spotfire_actionlog"
          adminUsername: "postgres"
          adminPasswordExistingSecret:
            name: "{{ .Release.Name }}-postgresql"
            key: "postgres-password"
          databaseUrl: "jdbc:postgresql://{{ .Release.Name }}-postgresql/"
        config-action-log-database-logger:
          databaseUrl: "jdbc:postgresql://{{ .Release.Name }}-postgresql/spotfire_actionlog"
          driverClass: "org.postgresql.Driver"
          username: "spotfire_actionlog"
          password: ""
          additionalOptions:
            pruning-period: 168
            log-local-time: false
