database:
  bootstrap:
    databaseUrl: "jdbc:postgresql://server:5432/spotfire"
    driverClass: "org.postgresql.Driver"
    username: "postgres"
    password: "postgresPassword"
  create-db:
    adminUsername: "postgres"
    adminPassword: "postgresPassword"
    databaseUrl: "jdbc:postgresql://server:5432/"
    doNotCreateUser: true
