apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spotfire-server.configJob.fullname" . | quote }}
  labels:
    app.kubernetes.io/component: configurator
    {{- include "spotfire-server.labels" . | nindent 4 }}
  annotations:
spec:
  ttlSecondsAfterFinished: {{ .Values.configJob.ttlSecondsAfterFinished }}
  template:
    metadata:
      {{- with .Values.configJob.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "spotfire-server.configJob.imagePullSecrets" . | nindent 6}}
      restartPolicy: Never
      initContainers:
      {{- if .Values.configuration.deployment.defaultDeployment.enabled }}
        - name: init-deployment
          image: {{ include "spotfire-server.configuration.deployment.defaultDeployment.image" . }}
          imagePullPolicy: {{ include "spotfire-server.configuration.deployment.defaultDeployment.image.pullPolicy" . }}
          command: ['sh', '-c', "mkdir -p /opt/spotfire/deployments-volume/${DEPLOYMENT_AREA_NAME}; cp /opt/spotfire/deployment-files/* /opt/spotfire/deployments-volume/${DEPLOYMENT_AREA_NAME}"]
          env:
            - name: DEPLOYMENT_AREA_NAME
              value: {{ .Values.configuration.deployment.defaultDeployment.deploymentAreaName | quote }}
          volumeMounts:
            - mountPath: /opt/spotfire/deployments-volume
              name: {{ default "deployments" .Values.volumes.deployments.existingClaim }}-volume
      {{- end }}
      {{- if .Values.configJob.extraInitContainers }}
        {{- tpl (toYaml .Values.configJob.extraInitContainers) $ | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "spotfire-server.serviceAccountName" . }}
      containers:
        - name: config-job
          command: ["/bin/sh","-c"]
          args: ["/opt/spotfire/scripts/main.sh"]
          image: {{ include "spotfire-server.configJob.image" . }}
          imagePullPolicy: {{ include "spotfire-server.configJob.image.pullPolicy" . }}
          envFrom:
          {{- if .Values.configJob.extraEnvVarsSecret }}
          - secretRef:
              name: {{ tpl .Values.configJob.extraEnvVarsSecret $ }}
          {{- end }}
          {{- if .Values.configJob.extraEnvVarsCM }}
          - configMapRef:
              name: {{ tpl .Values.configJob.extraEnvVarsCM $ }}
          {{- end }}
          env:
            {{- if .Values.configJob.extraEnvVars }}
            {{ tpl (toYaml .Values.configJob.extraEnvVars) $ | nindent 12 }}
            {{- end }}
            {{ include "spotfire-common.acceptEUAEnvVar" . | nindent 12 }}
            {{ include "spotfire-server.site.envVars" . | nindent 12 }}
            {{ include "spotfire-server.spotfireadmin.envVars" . | nindent 12 }}
            {{ include "spotfire-server.database.envVars" . | nindent 12 }}
            {{ include "spotfire-server.configVars" . | nindent 12 }}
            {{ include "spotfire-server.actionLog.envVars" . | nindent 12}}
            {{ include "spotfire-server.database.adminEnvVars" . | nindent 12}}
            - name: LOG_APPENDER
              value: "console"
            - name: LOG_LEVEL
              value: {{ .Values.configJob.logLevel | quote }}
            - name: JOB_CREATE_DATABASE
              value: {{ index .Values "database" "create-db" "enabled" | quote }}
            - name: JOB_UPGRADE_DATABASE
              value: {{ .Values.database.upgrade | quote }}
            {{- if or (eq .Values.configuration.apply "always") (eq .Values.configuration.apply "initialsetup") (eq .Values.configuration.apply "never") }}
            - name: JOB_WHEN_TO_APPLY_CONFIG
              value: {{ .Values.configuration.apply | quote }}
            {{- else }}
            {{- fail "apply must be one of always, never, initialsetup" }}
            {{- end }}
            - name: JOB_PREFER_EXISTING_CONFIG
              value: {{ .Values.configuration.preferExistingConfig | quote }}
            - name: JOB_DO_DEPLOY
              value: {{ .Values.configuration.deployment.enabled | quote }}
            - name: JOB_DO_DEPLOY_CLEAR
              value: {{ .Values.configuration.deployment.clear | quote }}
            - name: JOB_CONFIGURATION_COMMENT
              value: {{ printf "Helm configuration update - release=%s revision=%d" .Release.Name .Release.Revision }}
            - name: JOB_CREATE_ADMIN
              value: {{ .Values.configuration.spotfireAdmin.create | quote }}
          resources: {}
          volumeMounts:
            - name: config-job-scripts-volume
              mountPath: /opt/spotfire/scripts/
            {{- if .Values.configuration.commandScripts }}
            - name: command-scripts-volume
              mountPath: /opt/spotfire/command-scripts/
            {{- end }}
            {{- if .Values.configuration.preConfigCommandScripts }}
            - name: pre-config-command-scripts-volume
              mountPath: /opt/spotfire/pre-config-command-scripts/
            {{- end }}
            {{- if .Values.configuration.configurationScripts }}
            - name: configuration-scripts-volume
              mountPath: /opt/spotfire/configuration-scripts/
            {{- end }}
            {{- if (or .Values.volumes.deployments.existingClaim .Values.configuration.deployment.defaultDeployment.enabled) }}
            - name: {{ default "deployments" .Values.volumes.deployments.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/deployments
              subPath: {{ .Values.volumes.deployments.subPath | quote }}
            {{- end }}
            {{- if .Values.volumes.certificates.existingClaim }}
            - name: {{ .Values.volumes.certificates.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/certs
              subPath: {{ .Values.volumes.certificates.subPath | quote }}
            {{- end }}
            {{- if .Values.volumes.customExt.existingClaim }}
            - name: {{ .Values.volumes.customExt.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/custom-ext
              subPath: {{ .Values.volumes.customExt.subPath | quote }}
            {{- end }}
            {{- if .Values.volumes.customExtInformationservices.existingClaim }}
            - name: {{ .Values.volumes.customExtInformationservices.existingClaim }}-volume
              mountPath: /opt/spotfire/spotfireconfigtool/custom-ext-informationservices
              subPath: {{ .Values.volumes.customExtInformationservices.subPath | quote }}
            {{- end }}
            {{- with .Values.configJob.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        {{- with .Values.configJob.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: config-job-scripts-volume
          configMap:
            name: {{ .Release.Name }}-config-job-scripts
            defaultMode: 0755
        {{- if .Values.configuration.commandScripts }}
        - name: command-scripts-volume
          configMap:
            name: {{ .Release.Name }}-command-scripts
            defaultMode: 0755
        {{- end -}}
        {{- if .Values.configuration.preConfigCommandScripts }}
        - name: pre-config-command-scripts-volume
          configMap:
            name: {{ .Release.Name }}-pre-config-command-scripts
            defaultMode: 0755
        {{- end -}}
        {{- if .Values.configuration.configurationScripts }}
        - name: configuration-scripts-volume
          configMap:
            name: {{ .Release.Name }}-configuration-scripts
            defaultMode: 0755
        {{- end -}}
        {{- $existingVolumes := dict }}
        {{- if .Values.volumes.deployments.existingClaim }}
        {{- $claimName := .Values.volumes.deployments.existingClaim }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
        {{- else if .Values.configuration.deployment.defaultDeployment.enabled }}
        - name: deployments-volume
          emptyDir: {}
        {{- end }}
        {{- if .Values.volumes.certificates.existingClaim }}
          {{- $claimName := .Values.volumes.certificates.existingClaim  }}
          {{- if not (index $existingVolumes $claimName) }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
          {{- end }}
        {{- end }}
        {{ if .Values.volumes.customExt.existingClaim -}}
          {{- $claimName := .Values.volumes.customExt.existingClaim  }}
          {{- if not (index $existingVolumes $claimName) }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
          {{- end }}
        {{- end }}
        {{ if .Values.volumes.customExtInformationservices.existingClaim -}}
          {{- $claimName := .Values.volumes.customExtInformationservices.existingClaim  }}
          {{- if not (index $existingVolumes $claimName) }}
        - name: {{ $claimName }}-volume
          persistentVolumeClaim:
            claimName: {{ $claimName }}
            {{- $_ := set $existingVolumes $claimName true }}
          {{- end }}
        {{- end }}
      {{- with .Values.configJob.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configJob.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configJob.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
