apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    {{- include "spotfire-server.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-config-job-scripts
data:
{{ range $filepath, $content := .Files.Glob "config-job-scripts/*" }}
  {{ $content := $content | toString }}
  {{ $filename := $filepath | trimPrefix "config-job-scripts/" | trimSuffix ".gotmpl" }}
  {{- if hasSuffix ".gotmpl" $filepath }}
  {{ $filename }}: |
  {{- tpl $content $ | nindent 4 }}
  {{- else }}
  {{ $filename }}: |
  {{- $content | nindent 4 }}
  {{- end }}
{{ end }}